spring.application.name=DemiProjectWW

# SERVER
server.port=8080

#---DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/wealthwise_db1
spring.datasource.username=root
spring.datasource.password=MYsql@07#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#---JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#--JWT
app.jwt.secret=wealthwise_secret_key_2026_minimum_32_chars_long
app.jwt.expiration=86400000

#---GMAIL SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mumtazmulla725@gmail.com
spring.mail.password=emhgcmsyxkawxxes
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#---APP-----
app.frontend.url=http://localhost:3000
